name: Build VSFilter

on:
  push:
#    branches: [master, ci, build, xy_sub_filter_rc5]

jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        shell: 'bash'
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      # Doesn' work
      - name: install yasm
        shell: cmd
        run: |
          git clone https://github.com/ShiftMediaProject/VSYASM.git
          .\VSYASM\install_script.bat

      - name: Download YASM
        shell: powershell
        run: |
          mkdir yasm
          (New-Object Net.WebClient).DownloadFile('https://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe', 'yasm/yasm.exe')
          ls yasm
          echo "Install system-wide..."
          cp yasm\yasm.exe C:\windows\system32\yasm.exe
          ls C:\windows\system32\yasm.exe
          echo "Install for VS2019..."
          cp yasm\yasm.exe "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\yasm.exe"
          ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\yasm.exe"
          echo "Done."

      # VS2019 is 16.x;  VS2022 17.x
      - name: Setup VS2019
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      #    vs-version: '[16.01,16.11]'

#      - name: Show VS2019 dir
#        shell: cmd
#        run: |
#          tree "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" /f /a


      - name: Build xy-VSFilter
        run: |
          git fetch --all --tags
          #cmd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          bash ./build_vsfilter.sh -platform "x64" -compiler VS2019 -proj vsfilter
          printf '\n\n\n\n'
          ls -al

      - name: Publish output or actually everything
        uses: actions/upload-artifact@v2
        with:
          name: VSFilter+SubFilter-binaries
          path: |
            bin
            dist
